### ISSUE TITLE
Bookmarks button is broken in 0.9.7

### ISSUE THREAD

**Issue by dstd** [trol73/mucommander#105]
Nothing happens when I click on buttons above the files lists. All works in 0.9.5 and 0.9.6.
`Edit bookmarks`, `Explore bookmarks` menu commands works fine, and I can see items in `Bookmarks` menu. 

OS X 10.11.4

**Comment by trol73** [comment]
I do not quite understand what kind of buttons do you mean?

**Comment by dstd** [comment]
This one:
![2016-03-31 00-01-42](https://cloud.githubusercontent.com/assets/1444844/14157473/3790adc0-f6dc-11e5-9e6c-d7c93c4f85fb.jpg)

**Comment by trol73** [comment]
Hm.. I can't reproduce this issue

2016-03-31 1:02 GMT+04:00 Denis Stanishevsky notifications@github.com:

> This one:
> [image: 2016-03-31 00-01-42]
> https://cloud.githubusercontent.com/assets/1444844/14157473/3790adc0-f6dc-11e5-9e6c-d7c93c4f85fb.jpg
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/trol73/mucommander/issues/105#issuecomment-203635279

## 

  С уважением,
  Олег Трифонов
