### ISSUE TITLE
trolcommander does not show hidden files on FTP

### ISSUE THREAD

**Issue by Kisuke-CZE** [trol73/mucommander#118]
Hi,

I found a missing feature/bug in trolcommander.
It does not show hidden files (for example .htaccess) on remote FTP servers.

Even if I set this:

```
<ftp>
<list_hidden_files>true</list_hidden_files>
</ftp>
```

in file ~/.trolcommander/preferences.xml
I still can't access hidden files like .htacces

**Comment by trol73** [comment]
Can't reproduce that after SFTP library update
