### ISSUE TITLE
Encrease bookmarks popup window

### ISSUE THREAD

**Issue by papandreus1** [trol73/mucommander#123]
Current bookmarks popup window is too little - only 10 folders can be seen without scrolling. If you have more than 10 folders (usual case) it becomes not suitable to search desired folder in the list.

I think we should increase the window avoiding scroll until the popup window size equals to folder panel. May be see bookmarks window in other file manager, e.g. Total Commander - has bigger window for now

**Comment by trol73** [comment]
I will try to improve it

**Comment by trol73** [comment]
Fixed, the build is available on google drive
