### ISSUE TITLE
Debug release (release with detailed logs for submitting  issues)

### ISSUE THREAD

**Issue by papandreus1** [trol73/mucommander#125]
Sometimes I faced with issues which steps to reproduce can't be described simply.

E.g. after a few days of using the TrolCommander (without rerun the commander) when I switched to the commander window I can't scroll the file list using arrow buttons. (OS X)

I hope that it will be very useful to release additional builds for testing or using by the tool enthusiasts to submit issues with detailed log helping to figure out the issues causes.

**Comment by trol73** [comment]
You can enable loging in main menu -> Help -> Debug console. Yo will see logs after level selection

**Comment by papandreus1** [comment]
Ok, thanks. I think it needs to be mentioned somewhere. Could you add some info on your site, something like "How to report bug?" 

BTW I found this section only now, after 1 year usage:
"... For installation under MacOS need to unzip the file trolCommander-XXX.app.tar.gz into /Applications/ directory if you have installed Java 8. Elsewere use package trolcommander-XXX.app_with_java.tar.gz (since 0.9.4). "
For the last release (0.9.7) which did not have macos dmg I had to write some script to run easily without that info
So, I think downloading and installation details need to be highlighted, not be in the end of long text....

Thanks for your great efforts!!
