### ISSUE TITLE
[feature request] Add an option to turn off «left arrow on .. → previous directory» behaviour

### ISSUE THREAD

**Issue by alexander-pecheny** [trol73/mucommander#126]
Currently if the prompt is focused at «..» (see image below),
![](https://i.imgur.com/9OfoKtC.png)
and the user presses left arrow key, the pane drops to the parent folder. This may have been intended as a feature, but for a user not accustomed to this behaviour it is very annoying, as they constantly find themselves in a folder they have not intended to be in. Maybe it would be better to have an option to turn this behaviour off.

**Comment by trol73** [comment]
I think that current behaviour is ok - if you want to goto parent folder - you can press "left", elsewhere you don't press left )

**Comment by alexander-pecheny** [comment]
If I have already selected «..», it is OK. But most of the time it happens accidentally, when I just hold left to get closer to the beginning of a folder that contains many files.

**Comment by trol73** [comment]
I'm agree, it will be fixed in in the nearest release.
The first press of the left - go to the top of the table. The second press - go to the parent directory.

**Comment by warpkanal** [comment]
Different users, different opinions :)
I always configure my filemanagers to behave like (mu)trol: left goes to the parent directory immediately. If I just want to reach the topmost entry ".." I just hit the "Home" key.
I would at least want to configure it that way "Left = Go to parent" without first going to the top and only then going to the parent dir.

**Comment by trol73** [comment]
On Mac books you don't have the "Home" key :) And this feature can be useful here.
Now I have added two new commands - "Navigate left" and "Navigate right" with default hotkeys - "arrow left" and "arrow right". If you would use "arrow left" = "Go to parent" then you can assign "arrow left" hotkey as alternative accelerator of "Go to parent" action. Also you can assign "right arrow" hotkey as alternative accelerator for "Open" command.

**Comment by warpkanal** [comment]
You have Home key with Fn+Left arrow :)
Two commands makes sense, thx!

**Comment by trol73** [comment]
Yep, but "Fn+Left" arrow it's two buttons :)
"Go to parent" action already has "Backspace" hotkey, and easier to use it instead of "Fn+Left".
But I noticed that the new behavior is unusual for me - I also usually use "Left" to go back.. :)
