### ISSUE TITLE
Make file comparison window real modal window

### ISSUE THREAD

**Issue by papandreus1** [trol73/mucommander#132]
This is a bad experience that user can switch to parent window (main window with 2 panels) without closing file comparison tool. The main window don't react on any user actions without closing file comparison tool!
 It seems the file comparison tool was intended to be "modal window" but this case was not processed well.

My platform OSX Yosemite

**Comment by trol73** [comment]
Yes, I have the same issue. I will try to fix it

**Comment by trol73** [comment]
fixed
