### ISSUE TITLE
View (F3) and Edit (F4) doesn't work...

### ISSUE THREAD

**Issue by iMobCoding** [trol73/mucommander#133]
I am on OS X El Capitan 10.11.6
Java Runtime: 1.8.0_101

F3 and F4 don't work anymore. Pressing keys or clicking directly at the bottom panel, doesn't do anything. Latest commit it worked on was: 94b23d21bda9470a5dfcd24703fba9cf752cc064 from Jun 24th
And commit: c7ef1b59d2631ab649885ad79199021e91c0b13b from Jul 30th broke it...

Best

**Comment by trol73** [comment]
I can't reproduce that.
Can you run the application from terminal with command
`java /Applications/trolCommander.app/Contents/Java/trolcommander.jar`
and show the output?
Shift-F3 doesn't work too?

**Comment by iMobCoding** [comment]
Shift F3 works

Here is the output:
`Error: Could not find or load main class .Applications.trolCommander.app.Contents.Java.trolcommander.jar`

Btw, I am creating the app with "ant app" from the source directory, like always. It works with commit from Jun 24th but not with Jul 30th anymore

Best

**Comment by trol73** [comment]
Can you reproduce this issue with jar-file form last release? And from sources, if run with command "ant" ?

**Comment by iMobCoding** [comment]
Ok, I downloaded your latest 0.9.8 from distribution and it works.

But when I try to build app myself with "ant app" from the sources folder it doesn't work from the commit I state above. So maybe just the build.\* files are wrong?

Please advise because I don't know java at all and don't know what's the reason for this not to work. When I build your latest commit and trying to start it gives me an error popup "main class not found"...

Best
