### ISSUE TITLE
Problem with Manage Commands

### ISSUE THREAD

**Issue by trx222** [trol73/mucommander#135]
Menu Tools (in german "Werkzeuge") - Commands ("Bearbeite Befehle") - Other ... I can not add commands, or I don't understand this function. After insert a new one and closing the window its gone and next time the list is emty. 
Is this Function for adding command to the Tools Menu? I'd like to add commands/functions which I can start with parameter (selected files or folders from both panels) for example to start a Folder-Compare Application without the need of coping paths ...

I'm using OS X with latest release.

**Comment by trol73** [comment]
Here is my configuration - command view used for customisation of F3-viewer.
![Commands](https://api.monosnap.com/rpc/file/download?id=zWO3I2YbpCXzw40o3Geva7dTkmlYwW)

This dialog - is editor for configuration file '~/Library/Preferences/trolCommander/commands.xml'

Here is my config

```
<?xml version="1.0" encoding="UTF-8"?>
<commands>
    <command alias="edit" value="open $f" filemask="*.doc" display="Edit doc"/>
    <command alias="edit" value="open -a gimp $f" filemask="*.png,*.jpg,*.jpeg" display="Edit images"/>
    <command alias="view" value="qlmanage -p $f" filemask="*.ppt,*.wav,*.mp3,*.pdf,*.rtf, *.icns,*.jpg,*.mp4,*.tif,*.tiff,*.stl,*.gif" display="view"/>
    <command alias="view" value="open $f" filemask="*.djv,*.djvu" display="viewDjvu"/>
</commands>
```

**Comment by trx222** [comment]
OK, I will try to edit the config directly. Is there a possibility to use a second (selected) file/folder (also from second/other panel) with a placeholder to give it as parameter to a command?

**Comment by trol73** [comment]
Currently that's not possible. It might be useful to diff-utility, but other uses this feature I don't see..

**Comment by trx222** [comment]
ok, I think your right

**Comment by trx222** [comment]
OK - second need would be a folder sync software like "compare" or similar tools ... I think it can be also a nice tool included in trolcommander :)
third: to combine files ... put to audios together, merge to images

**Comment by trx222** [comment]
@trol73 Is there a way to add hotkeys to the edit commands? So that I don't have to use the mouse with "open with ..." command?

**Comment by trol73** [comment]
How about F4 hotkey?

**Comment by trx222** [comment]
I need it for different editors. F4 should stay the default ...

**Comment by trol73** [comment]
As variant, you can configure several viewers for this type of file. And then use Shift+F3 hotkey to choice editor.

And ideally, it would be worth to add to UserMenu (available on F1 hotkey, not yet fully implemented and documented) support for commands only for specific file types...

**Comment by trx222** [comment]
The way with Shift+F3 is already great for me :) maybe for later its a way to add Shift+F4 too. Thank you very much for your answer, will again donate something on your page.

**Comment by trol73** [comment]
Thank you very much. 
I will try to add a similar menu for Shift+F4

**Comment by trol73** [comment]
I added the "Edit as..." menu (Shift-F4) (latest jars are available on GoogleDrive)
