### ISSUE TITLE
Hex view fails for SFTP file

### ISSUE THREAD

**Issue by andreitokar** [trol73/mucommander#138]
Shit+F3, select Hex view on SFTP file, and action fails with exception:
java.lang.ClassCastException: com.mucommander.commons.file.impl.sftp.SFTPFile$3 cannot be cast to com.sshtools.sftp.SftpFileInputStreamEx
	at com.mucommander.commons.file.impl.sftp.SFTPFile$SFTPRandomAccessInputStream.<init>(SFTPFile.java:924)

**Comment by trol73** [comment]
I have fixed this issue, thanks!
