### ISSUE TITLE
"File collision" options

### ISSUE THREAD

**Issue by pawelantczak** [trol73/mucommander#141]
Hello.

Is it possible to add other options to "File collision".
Now we have only Cancel and Skip.
I would like to have possibility to Rename or Overwrite file.

Regards.

**Comment by trol73** [comment]
Hello,
it's already implemented for Copy and Move operations:
![file collision](https://cloud.githubusercontent.com/assets/3051107/21845207/2902c598-d80b-11e6-937c-1f8be35c8fa7.png)

**Comment by pawelantczak** [comment]
Yes. If files are different directories.
When I want to have copy of a file in current dir, there are only Cancel and Skip options available.
<img width="509" alt="screen shot 2017-01-11 at 11 44 02" src="https://cloud.githubusercontent.com/assets/171534/21845549/6442b108-d7f3-11e6-938c-a02b0b89c6e4.png">

**Comment by trol73** [comment]
In this case just press Shift+F5 and make copy with different name :)
