### ISSUE TITLE
[feature request] calculate size of folder on mark with space

### ISSUE THREAD

**Issue by trx222** [trol73/mucommander#143]
I know this feature from total commander - if you mark a folder it calculates the size of it and display instead of <DIR>.

**Comment by oujesky** [comment]
I actually have this implemented in my local fork, but I was not able to separate this task easily only for spacebar - I have it together with the mark action, which may be triggered also by other keys (insert by default). I may put it her as experimental PR, but someone more familiar with mucommander/trolcommander internals might find a better solution.

**Comment by trol73** [comment]
I think  it can be made configurable.
For example a checkbox "Calculate folder size on select" in the Preferences dialog
