### ISSUE TITLE
Black on black in binary viewer

### ISSUE THREAD

**Issue by dstd** [trol73/mucommander#146]
If user wants to set light background in file viewer/editor he should set a text color to dark to make text visible. So in binary viewer every second row will be a dark on a dark, because there's no option for alternative background of rows.

![black on black](https://cloud.githubusercontent.com/assets/1444844/22712731/f567ec76-ed96-11e6-86fa-f4ebb639efac.jpg)

**Comment by trol73** [comment]
I'll add setting panel for hex viewer

**Comment by trol73** [comment]
![color settings window](https://api.monosnap.com/rpc/file/download?id=xiuCgIih8EQCcqGyYJcidHWGunrN0V)

Done :)
