### ISSUE TITLE
Hard to get started with trolCommander

### ISSUE THREAD

**Issue by rdiez** [trol73/mucommander#152]
I am looking for a sensible file manager, which is surprisingly hard, and I wanted to build trolCommander on my Linux PC and play with it a little.

To begin with, there are 2 readme files in the Git repository, which is a bit confusing. In readme.txt , the links http://trac.mucommander.com/ and http://www.mucommander.com/forums seem to be broken.

There is no e-mail address or mailing list to ask questions.

I could not find any build instructions. I have some experience with Java, but mainly with NetBeans, so I tried to open the project with NetBeans 8.1. The project uses Maven, which I know nothing about. After some minutes of downloading, I get the following error message:

cd /home/rdiez/rdiez/trolCommander; JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 /home/rdiez/rdiez/netbeans-8.1-bin/java/maven/bin/mvn install
Scanning for projects...

Some problems were encountered while building the effective model for org.raisercostin:trol-commander:jar:0.10.0-SNAPSHOT
'build.plugins.plugin.version' for com.github.wvengen:proguard-maven-plugin is missing. @ line 739, column 12
'dependencies.dependency.systemPath' for sshtools:j2ssh-maverick:jar refers to a non-existing file /home/rdiez/rdiez/trolCommander/lib/runtime/sshtools/j2ssh-maverick-1.5.4.jar @ line 204, column 16
'dependencies.dependency.systemPath' for com.fifesoft:rsyntaxtextarea:jar refers to a non-existing file /home/rdiez/rdiez/trolCommander/lib/runtime/rsyntaxtextarea-2.6.0-SNAPSHOT.jar @ line 232, column 16

It is highly recommended to fix these problems because they threaten the stability of your build.

For this reason, future Maven versions might no longer support building such malformed projects.

                                                                        
------------------------------------------------------------------------
Building trolCommander 0.10.0-SNAPSHOT
------------------------------------------------------------------------
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.401s
Finished at: Mon Apr 17 10:55:46 CEST 2017
Final Memory: 12M/209M
------------------------------------------------------------------------
Failed to execute goal on project trol-commander: Could not resolve dependencies for project org.raisercostin:trol-commander:jar:0.10.0-SNAPSHOT: The following artifacts could not be resolved: sshtools:j2ssh-maverick:jar:1.5.4, com.fifesoft:rsyntaxtextarea:jar:2.5.6: Could not find artifact sshtools:j2ssh-maverick:jar:1.5.4 at specified path /home/rdiez/rdiez/trolCommander/lib/runtime/sshtools/j2ssh-maverick-1.5.4.jar -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Thanks in advance,
  rdiez

**Comment by trol73** [comment]
I use ant to build a project and it builds the project without problems for me
