### ISSUE TITLE
Could not build

### ISSUE THREAD

**Issue by Ygarr** [trol73/mucommander#153]
mvn package:

 Failed to execute goal on project trol-commander: Could not resolve dependencies for project org.raisercostin:trol-commander:jar:0.10.0-SNAPSHOT: The following artifacts could not be resolved: sshtools:j2ssh-maverick:jar:1.5.4, com.fifesoft:rsyntaxtextarea:jar:2.5.6: Could not find artifact sshtools:j2ssh-maverick:jar:1.5.4 at specified path /home/user/Software/mucommander/lib/runtime/sshtools/j2ssh-maverick-1.5.4.jar -> [Help 1]

**Comment by trol73** [comment]
I recommend using ant, it works fine
