### ISSUE TITLE
Scrolling issues on macOS High Sierra

### ISSUE THREAD

**Issue by bagonyi** [trol73/mucommander#162]
I have been using trolCommander for several years now on my Macbook, never had any issues. Last week my computer crashed and had to do a clean reinstall (macOS 10.13.3 - High Sierra). I have installed Oracle JDK 8, downloaded trolCommander from the releases tab, but for some reason I get the following behaviour when I **slowly** swipe my fingers down on my Macbook's trackpad:

![trolcommander-scrolling-issue](https://user-images.githubusercontent.com/604444/36595143-f6117fa6-1898-11e8-8153-24d919f38074.gif)

Basically, when I try to scroll down slowly, it scrolls up. When I get to the middle of the top item in the file view, it jumps down to show the next item. This keeps repeating, I keep swiping down on the trackpad but it keeps scrolling up instead. I can only scroll down if I do a longer / quicker swipe on the trackpad. 

Interestingly I don't have this issue on the latest muCommander, nor any other Java app. I have tried all versions trolCommander that were released, they exhibit the same problem. I have also tried different JVMs, Oracle 9 and Zulu 8 & 9 but that didn't help either. I have tried searching through the commits that might have introduced this issue recently, but could not find any commits with "*scroll*" recently.

When using an ordinary USB mouse, scrolling with the trackball it is all fine, however that isn't meant to give the "smooth scrolling" experience. It jumps 2-3 lines at a time.

When I try scrolling up it seems to be all fine.

Is there anything else I could do to help investigate this problem?

**Comment by trol73** [comment]
I have reproduced this issue. I'll try to fix it.

**Comment by trol73** [comment]
Fixed, thanks.
The last build is here: https://drive.google.com/drive/u/0/folders/0BwgV75Rd8itZYzV4NDNiSGllM3c

**Comment by bagonyi** [comment]
Works all OK. Thank you for looking into it!
