### ISSUE TITLE
Unable to load Java Runtime Environment on macOS Catalina 10.15.6

### ISSUE THREAD

**Issue by yaroslav-v** [trol73/mucommander#172]
Hi!

Thanks again for great additions to muCommander. Personally, I prefer to use trolCommander even over an updated version of mu.

However, I've faced a problem when switched to macOS Catalina. For some unknown reason trolCommander doesn't want to launch and shows Unable to load Java Runtime Environment message.

I have installed Open JDK 8 and $JAVA_HOME set as well:
```
~ % echo $JAVA_HOME                                 
/Library/Java/JavaVirtualMachines/openjdk8/Contents/Home
~ % java -version                                   
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
```

Unfortunately, the app doesn't start neither from Applications folder nor from console via `open -a trolCommander.app`

However, I'm able to use it with `java -jar trolCommander.jar`

Additionally, I've found a few records in the system console and attached here. Looks like something is wrong with JavaAppLauncher. Hope it will help to resolve the issue.
[trolCommander_log.txt](https://github.com/trol73/mucommander/files/5327195/trolCommander_log.txt)

**Comment by trol73** [comment]
Have you tried using Oracle JRE 8 instead of OpenJDK 8?

**Comment by yaroslav-v** [comment]
Damn, you're right. It works fine with Oracle JDK/JRE 8.

I've tried the latest Oracle JDK 15 initially, but the app had other issues (couldn't find obsolete classes etc.)

Thx
