### ISSUE TITLE
Retina support

### ISSUE THREAD

**Issue by trol73** [trol73/mucommander#59]
see http://trac.mucommander.com/ticket/518

**Comment by VladRassokhin** [comment]
To support HiDPI images/icons would recommend you [iconloader](https://github.com/bulenkov/iconloader) library.

**Comment by and7ey** [comment]
I also would like to have Retina supported. Currently it is impossible to use trolCommander on such screens, see how it looks now - http://habrastorage.org/files/472/9b0/fe5/4729b0fe5ba74025951e67c2eb44a43a.png

**Comment by trol73** [comment]
I can I see on my non-retina display, the main problem here is toolbar icons?

**Comment by and7ey** [comment]
The main problem I observe is with fonts - they are blurred (смазаны/размыты)

**Comment by trol73** [comment]
What version of JRE do you use?

**Comment by and7ey** [comment]
```
MB:~ me$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
```

**Comment by trol73** [comment]
Hmm.. trolCommander doesn't support Java 1.6, it compiled now for 1.7.
I try to google the problem and found this: http://bulenkov.com/2013/06/23/retina-support-in-oracle-jdk-1-7
Perhaps the issue can be related with JRE version. The package trolcommander-0_9_4.app_with_java.tar.gz contains JRE 1.7.0_40.

**Comment by trol73** [comment]
You can see JRE version in About trolCommander dialog

**Comment by and7ey** [comment]
Right, I use the version with built-in JRE:

```
Java
Runtime version: 1.7.0_40
VM name: Java HotSpot(TM) 64-Bit Server VM
VM version: 24.0-b56
VM vendor: Oracle Corporation
```

**Comment by trol73** [comment]
Do you try to play with font names and sizes? 
Also I suggest to use last build - it supports a file icons in hight resolutions.
For that you need to download last jar-file from nightly builds on google drive and update. Also in Preferences -> Appearance -> "Use system file icons" select Always. Also you can here increase icon sizes, for retina it may be useful.

**Comment by trol73** [comment]
How to fix Retina issue: http://help.infinitekind.com/discussions/problems/4227-macbook-pro-retina-display-support

**Comment by magicgoose** [comment]
For me, it renders text good (using full resolution). Maybe there are other problematic areas, didn't test everything yet.

**Comment by trol73** [comment]
Retina support implemented now
