### ISSUE TITLE
Can't find an option to change the Terminal application

### ISSUE THREAD

**Issue by dertuxmalwieder** [trol73/mucommander#64]
I'd like to integrate iTerm2 as the "Terminal" in trolCommander. Is there a way to do so? The documentation (of muCommander) doesn't mention such.

**Comment by trol73** [comment]
I will implement that on the next release. Now the terminal command is hardcoded

**Comment by dertuxmalwieder** [comment]
Thanks for the implementation. :) Nice support!

**Comment by trol73** [comment]
implemented
