### ISSUE TITLE
Can't copy mac os framework correctly.

### ISSUE THREAD

**Issue by hutchdog** [trol73/mucommander#65]
Your fork share same bug with a muCommander. When you are trying to copy any framework from the one folder to another a result will be damaged. The problem is .framework is a folder with a files and an internal links, which are necessary for a framework and which are must be restored after a copy. Finder does it in correct way.

**Comment by trol73** [comment]
Good point, that will be fixed in the next version

**Comment by trol73** [comment]
Fixed - copy of symbolic link is supported now
