### ISSUE TITLE
Settings aren't stored on exit

### ISSUE THREAD

**Issue by agnarodegard** [trol73/mucommander#66]
First I want to thank you for the job you're doing. I've been using mucommander for a long time but was getting tired of bugs. I just find trolcommander and I'm extremely happy!

To show my appreciation, here's a bug:

Installed trolcommander via .deb archive. Set bookmarks etc but upon restart they aren't there anymore. I still had my old xml-files from muCommander. When copying these over to .trolcommander configuration is saved correctly (including new changes). It seems that the problem is that some files aren't created in .trolcommander upon installation.

**Comment by trol73** [comment]
Fixed
