### ISSUE TITLE
trolcommander losing keyboard input

### ISSUE THREAD

**Issue by agnarodegard** [trol73/mucommander#67]
Sometimes trolcommander lose the ability to register keys from the keyboard. I can't reproduce it reliably, but it happens frequently when I'm using shortcuts "too fast" or something. Copying files, editing, tab-ing... I'm in the zen of filemanagement and then suddenly no shortcuts work anymore. The mouse works. Restarting trolcommander resolves the issue. This is my biggest pain point for this otherwise excellent program. It's hands down the best double-pane filemanager on linux.

**Comment by trol73** [comment]
I haven't seen this issue. But I noticed that sometimes all dialog boxes are opened twice. For example, Cmd+F opens once two search dialog on file panel or text viewer/editor. And in this case restarting program resolves this issue too. It's probably the same bug.

**Comment by agnarodegard** [comment]
Here's a way I can somewhat reliably reproduce the bug: If you have two different dirs open, each with a copy of a file with the same name. It could just be a text file (test.txt). When I hit 'F5' to copy I get a dialog asking to override or cancel, hit 'o' for override. In 20%-50%f of the cases, I lose keyboard input after this operation. I also lose input when copying a new file to a dir, but then only in 10%-20% of the cases. You can do it slowly, speed doesn't seem to be an issue.

I'm on a Lenovo W530 thinkpad running ubuntu 14.04 LTS. Here's the output of java --v:
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

I've experienced this exact problems on all installations of mucommander, also on other hardware, like a Lenovo T400 Thinkpad running ubuntu 12.04/12.10.

I'm also attaching a screenshot of the debug console. I couldn't find a text log anywhere and no option to export the content.
![trolcommander-debugsoncolse](https://cloud.githubusercontent.com/assets/5804387/4929596/77d50526-6555-11e4-8abc-6fec9d1dfebd.png)

Thanks for looking into this!

**Comment by trol73** [comment]
Can't reproduce this issue on Windows XP & MacOS with Oracle JRE. Will try test in on Fedora linux

**Comment by Keltek** [comment]
Confirm described behavior on Fedora 21 and Oracle JRE 1.8.0_40-b26 x86-64.

**Comment by Keltek** [comment]
Isn't this related?
http://tools.android.com/knownissues/ibus
Testing now first workaround…

**Comment by Keltek** [comment]
I test this issue according to this commit https://github.com/trol73/mucommander/commit/ab3f311e045dc415db51b91a8ddcff2f069fe7dc and it is now works flawlessly :+1:
It can be closed. Thank you.
