### ISSUE TITLE
Auto-completion of path on rename/copy

### ISSUE THREAD

**Issue by bzamecnik** [trol73/mucommander#68]
When the user open the rename or copy dialog it would be great if the path textbox could auto-complete the path the same way as the in the path textbox on top of the file commander panel. There is is completed via the DOWN key. On the other hand CTRL+SPACE known from almost every IDE would be probably most intuitive.

**Comment by trol73** [comment]
The autocompleter in the copy dialog is already implemented in muCommander. Do you have any problems with it?

**Comment by bzamecnik** [comment]
Really? How does it activated? I didn't find any way to do it. (I have looked at the source code yet...)

**Comment by trol73** [comment]
The input component in the copy dialog is the same as in the path textbox on top of the file commander panel. It's activated by DOWN or CTRL+SPACE or displays automatically after some delay. I have checked that on MacOS and WindowsXP

**Comment by bzamecnik** [comment]
Aha! Well, for absolute paths it really works. On the other hand it doesn't work where I expected - on paths relative to the current directory of the panel. Anyway, thanks for information!

**Comment by trol73** [comment]
Closed because I don't see any problems with autocompleter now
