### ISSUE TITLE
Unpacking doesn't work

### ISSUE THREAD

**Issue by yaroslav-v** [trol73/mucommander#77]
Unpacking process isn't starting when I'm trying to unpack archive (zip, tgz etc.) from menu File->Unpack or through shortcut. Only dialogs were showed but progress isn't moving at all.

Packing works correcly. I even can see archive contents (through Enter) and copy it to external dirs.

Environment: trolCommander 0.9.5, MacOS 10.10.3

**Comment by trol73** [comment]
Thanks, it will be fixed

**Comment by trol73** [comment]
Now it's working for me

**Comment by yaroslav-v** [comment]
Yep, all works fine. Thanks.
