### ISSUE TITLE
GitHub Releases feature

### ISSUE THREAD

**Issue by alexey-lysiuk** [trol73/mucommander#83]
_This is just a question rather than an issue report_

Why don't you use GitHub Releases feature?
Just tag a particular commit (with a regular tag, not a lightweight one) and it will appear in Releases. Then you can draft a new release by selecting the tag, adding change log and uploading binaries.
The separate repository with binaries isn't the best choice IMHO.

I would like to make a pull request, but AFAIK tags cannot be added via pull requests.

**Comment by trol73** [comment]
Thanks for the suggest, I didn't known about this feature. I have created first release on GitHub

**Comment by alexey-lysiuk** [comment]
You can create all releases if you want to, as you can tag any particular commit, not only a HEAD.
Also, you can even remove the 0.9.6 tag and add it to the actual commit for this version.

**Comment by hovancik** [comment]
I added this to [homebrew cask](https://github.com/caskroom/homebrew-cask) so folks on OS X can install using `brew cask install trolcommander`.
