### ISSUE TITLE
"Sticky" cursor

### ISSUE THREAD

**Issue by reneverschoor** [trol73/mucommander#89]
OSX Yosemite and El Capitan
I had this problem also in muCommander.

Very often my cursor gets "sticky".
E.g. in the right panel the cursor line is on the 6th line.
No matter how often I press arrow up and arrow down, the cursor line jumps immediately back to the 6th line.
Only when I click with my mouse on another file, it gets unstuck, and I can move around normally.

I haven't been able to identify when the sticking starts, what triggers it.

It's driving me nuts...

**Comment by magicgoose** [comment]
Same problem here, it usually happens after dragging something onto another application from muCommander.

**Comment by trol73** [comment]
Thanks for this information - the issue is really related with D&D operations. Looks like this is issue in Java Swing framework. I have fixed it, check the last "nightly" build from GoogleDrive
