### ISSUE TITLE
Show Folders Size is not a toggle

### ISSUE THREAD

**Issue by Kafkamorph** [trol73/mucommander#94]
Having to click View-Show Folders Size after every chdir is a pain. This toggle should just be.. a toggle. A permanent one.

**Comment by papandreus1** [comment]
I don't think it should be permanent since for big folders it will take much time. 
The option is not a toggle (no check sign at the left)

**Comment by trol73** [comment]
I don't think it should be permanent too. You can configure hotkey to show folders size and press it when folder size need
