### ISSUE TITLE
"File collision" dialog is broken — all items are not clickable

### ISSUE THREAD

**Issue by magicgoose** [trol73/mucommander#95]
I'm talking about this dialog (right one):
![screen shot 2016-01-23 at 2 24 03 pm](https://cloud.githubusercontent.com/assets/1442206/12529941/a2eec4be-c1dd-11e5-8e0b-e29f69023c25.png)

All items inside the right dialog do not react to mouse clicks at all. (but I can close both of them by pressing Esc key).

The system is OS X 10.11.2; using this build: `https://github.com/trol73/mucommander/releases/download/v0.9.7/trolcommander.jar`

**Comment by magicgoose** [comment]
Also, using Oracle JRE 1.8.0_60

**Comment by trol73** [comment]
I can't reproduce that on MaxOS X 0.11.2 with java  1.8.0_65

**Comment by magicgoose** [comment]
it _might_ be related to the fact that I also use SmoothMouse. (but other apps do work without problems anyway)

**Comment by trol73** [comment]
Looks like that is issue with SmoothMouse
