### ISSUE TITLE
[OS X] …today, it stopped launching (only splash does show up)

### ISSUE THREAD

**Issue by magicgoose** [trol73/mucommander#98]
After the splash window goes off, main window doesn't appear.
Where can I look for logs or any other traces of trouble?

**Comment by trol73** [comment]
You can execute trolCommander from terminal
java -jar /Applications/trolCommander.app/Contents/Java/trolcommander.jar
and see errors

**Comment by magicgoose** [comment]
So I ran `java -jar /Applications/trolcommander-0_9_7.app/Contents/Java/trolcommander.jar > trolcommanderLog.txt 2>&1`
And here is the log: https://gist.github.com/magicgoose/45753e20536bf80afa48

**Comment by trol73** [comment]
Thanks, I have fixed this NPE error. Could you try the last nightly build from google drive?

**Comment by magicgoose** [comment]
Yes, where can I find them?

**Comment by trol73** [comment]
You can find the link on project page http://trolsoft.ru/en/soft/trolcommander

**Comment by magicgoose** [comment]
Unfortunately, project's website doesn't support HTTPS, so there is no protection from tampered links, etc.

Thank you for the link, will try soon.

**Comment by magicgoose** [comment]
Yes, it does work. May I ask you to make a complete new release (with .app)?

**Comment by trol73** [comment]
The new app will be in future with new release. Currently you can manually patch existing .app with replacing old jar file to new jar
