### ISSUE TITLE
Unable to load Java Runtime Environment on OSX El Capitan

### ISSUE THREAD

**Issue by dbogdanov** [trol73/mucommander#99]
I've installed Java 8 following [this guide](https://oliverdowling.com.au/2015/10/09/oracles-jre-8-on-mac-os-x-el-capitan/).

```
java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
```

trolCommander fails on startup with the error: "Unable to load Java Runtime Environment".

My older version of muCommander runs fine.

**Comment by trol73** [comment]
Can you try to run trolCommander.jar from command line?

java -jar trolCommander.jar

**Comment by dbogdanov** [comment]
Actually, it runs successfully when I run this command from Contents/Java folder. Running the app fails.

**Comment by twox** [comment]
I have same problem.
Result of command: java -jar trolCommander.jar

```
$java -jar trolCommander.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/mucommander/TrolCommander : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

```

**Comment by trol73** [comment]
Wrong Java Runtime version, trolCommander required Java 8

**Comment by twox** [comment]
After update Java from [http://www.oracle.com/technetwork/java/javase/downloads/index.html](http://www.oracle.com/technetwork/java/javase/downloads/index.html), works fine
Thanks!

**Comment by dbogdanov** [comment]
What is the reason that the application runs fine from the terminal, but fails to lunch from Applications menu?

**Comment by twox** [comment]
Try to run app from package:

```
admin$ cd /Applications/trolCommander.app/Contents/Java
iMac-admin:Java admin$ java -jar trolCommander.jar
```

**Comment by dbogdanov** [comment]
This works fine, but i can't run it without using console.

**Comment by twox** [comment]
А что пишет в консоли сообщений системы?
Какие ошибки туда лезут?

**Comment by dbogdanov** [comment]
```
(com.mucommander.trolCommander.424992[788]) Service exited with abnormal code: 1
```

**Comment by twox** [comment]
И это весь лог, странно?
Что выдают команды в терминале?:  $ which java 
и $ echo $PATH

**Comment by dbogdanov** [comment]
```
which java
/usr/bin/java

echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

**Comment by twox** [comment]
Странная ситуация. 
Окружение вроде доступно и путь верный.
Пробовал ставить java по ссылке из пакета?  [ http://www.oracle.com/technetwork/java/javase/downloads/index.html](http://www.oracle.com/technetwork/java/javase/downloads/index.html) 
Проверь права доступа и действия антивируса, если стоит...

**Comment by trol73** [comment]
Такое ощущение, что MacOS  использует какую-то свою JRE и берёт её не из $PATH ..

**Comment by dbogdanov** [comment]
Поставил на другую свежую систему (MacOS Sierra), все работает.
